### ISSUE TITLE
PUT does not work for route /podcasterinnen/[id]

### ISSUE THREAD

**Issue by Fischaela** [podcasterinnen/chosen-api#12]
Error message:
```
ERROR 23503 (foreign_key_violation): update or delete on table "tags" violates foreign key constraint "podcasters_tags_tag_id_fkey" on table "podcasters_tags"

table: podcasters_tags
    constraint: podcasters_tags_tag_id_fkey

Key (id)=(121) is still referenced from table "podcasters_tags".
```

This is the request I am senden via Postman:

```javascript
var data = JSON.stringify({
  "podcaster": {
    "forename": "Michaela",
    "city": "Berlin",
    "country": "Deutschland",
    "surname": "Lehr",
    "tags": "Buffy, Stricken, Yoga"
  }
});

var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("PUT", "http://localhost:4000/podcasters/63");
xhr.setRequestHeader("Content-Type", "application/json");
xhr.setRequestHeader("Cache-Control", "no-cache");
xhr.setRequestHeader("Postman-Token", "8a31f101-4b17-4797-bbd5-96e1a0fc318f");

xhr.send(data);
```

**Comment by haslinger** [comment]
You have to specify the :on_delete and :on_replace behaviour on the many_to_many relation, https://hexdocs.pm/ecto/Ecto.Schema.html#many_to_many/3-removing-data to get those records handled automatically. See the paragraph above for the options available.

**Comment by Fischaela** [comment]
Yeah, that's what I tried, but couldn't get it to work. Did it work for you?

**Comment by haslinger** [comment]
It's missing here: https://github.com/podcasterinnen/chosen-api/blob/master/lib/chosen_api/profiles/podcaster.ex#L26 .

No, I didn't try myself, but it's the standard way to do it, search for the string "It makes sense in this case that we want to delete relationships in the join table posts_tags when updating a post with new tags." in the docs for associations: https://hexdocs.pm/ecto/associations.html
