### ISSUE TITLE
Instead of only "remote possible" we could have a whole podcasting section with checkboxes or sth similar

### ISSUE THREAD

**Issue by Fischaela** [podcasterinnen/chosen-api#16]
Mögliche Punkte:
"Dazu kann man mich anfragen" - Vielleicht: "Skills/Aktivitäten" 

* Ich halte Vorträge.
* Ich gebe Workshops/Schulungen.
* Ich kann remote aufnehmen.
* Ich nehme auch fremdsprachige Podcasts auf.
* Ich nehme auch Podcasts draußen auf.
* Ich lade auch Gästinnen ein.
* Ich reise auch um Podcasts aufzuzeichnen.
* Ich kann Podcasts schneiden, aufnehmen und produzieren. 

Offene Fragen:
* Wollen wir eine solche Section im Profil? - Ja wollen wir.
* Wie könnte man die Section betiteln? - s.o.
* Welche Fragen sollten in der Section gestellt werden? - s.o.
* Ist eine Checkbox-Liste das beste Pattern? - Ja, fidne ich gut. 
* Passt das zusammen mit der Info "Dazu kann man mich anfragen" (z.B. Vorträge, Workshops, etc.)
* Passt das zusammen mit der Info "Ich mache Podcasts professionell/als Hobby"? Wollen wir diese Info im Profil? - Nein, denn nur weil jemand es als Hobby macht, muss es nicht weniger professionell sein.

**Comment by diehorst** [comment]
Tauchen dann nur die True Skills auch auf der Webseite auf? Oder werden auch die False angezeigt? Ich habe die Aktivitäten etwas sortiert und umgestellt. Für mich passt das jetzt so.

**Comment by Fischaela** [comment]
Hm, was wäre denn besser? Aus Layout-Sicht tendiere ich instinktiv zur Variante dass False und True angezeigt wird.

**Comment by diehorst** [comment]
Besser weiß ich gar nicht. Ist eher die Frage was schöner aussieht. Also, dann beide anzeigen.
