### ISSUE TITLE
As podcasterin I want to submit a new tag

### ISSUE THREAD

**Issue by Fischaela** [podcasterinnen/chosen-api#19]

**Comment by Fischaela** [comment]
Idee: Wir verlinken den entsprechenden Github Issue (https://github.com/podcasterinnen/chosen-client/issues/84) bei dem dann jeder als Kommentar neue Tags vorschlagen darf. Abgestimmt wird über die Daumen hoch. Wenns viele Daumen hoch gibt und wir ihn okay finden, bauen wir ihn ein. @diehorst Was denkste?

**Comment by diehorst** [comment]
Ich finde die Idee gut, frage mich allerdings, ob das nicht zu viel
technisches Verständnis voraussetzt. Was meinst du?

**Comment by Fischaela** [comment]
Ja, frage ich mich auch und kann ich schwer einschätzen.

dieHorst <notifications@github.com> schrieb am Di., 13. Nov. 2018 um
13:23 Uhr:
