### ISSUE TITLE
As a developer I don´t want a space in "Danielas Podcasts" 

### ISSUE THREAD

**Issue by diehorst** [podcasterinnen/chosen-api#51]
<img width="319" alt="Bildschirmfoto 2022-04-28 um 08 27 27" src="https://user-images.githubusercontent.com/37985185/165690755-7f557f17-7e51-4878-868f-82f302ae162c.png">

**Comment by diehorst** [comment]
Auf unserer Webseite ist diese Bug nicht. Dort steht "Danielas Podcasts".

**Comment by Fischaela** [comment]
moved to client repo
