### ISSUE TITLE
As a developer I don´t want a Space in "Danielas Refernzen

### ISSUE THREAD

**Issue by diehorst** [podcasterinnen/chosen-api#52]
<img width="337" alt="Bildschirmfoto 2022-04-28 um 08 29 04" src="https://user-images.githubusercontent.com/37985185/165691048-ce99d189-6720-45df-a864-92fea0e2716c.png">

**Comment by diehorst** [comment]
Auf unserer Webseite ist diese Bug nicht. Dort steht "Danielas Referenzen".

**Comment by Fischaela** [comment]
moved to client repo
