### ISSUE TITLE
As a Podcaster*in I don't want to lose my changes if I use "Enter"

### ISSUE THREAD

**Issue by diehorst** [podcasterinnen/chosen-api#53]
Wenn ich in den Feldern Name, Nachname, in den Referenz- und Podcastfelder sowie bei Sprache "Enter" nutze um ins nächste Feld zu springen, verliere ich meine Änderungen. Es betrifft alle einzeiligen Spalten.

Wenn ich "Enter" nutze springt das Profil um, als hätte es gespeichert. Ich muss erneut auf "Bearbeiten" gehen um meine Änderungen erneut einzugeben. 

Wenn ich in den mehrspaltigen Textfeldern "Enter" nutze, springt er in die nächste Zeile. Bei den Tags passiert nichts. Er behält den neuen Tag und ich kann mein Profil weiter bearbeiten.

**Comment by Fischaela** [comment]
moved to client repo
